version: '3.9'

x-healthcheck: 
  &healthcheck
  test: curl -f http://localhost/
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 10s

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=Vulnogramm
    expose:
      - 5432
    volumes:
      - ./init-databases-tables.sh:/docker-entrypoint-initdb.d/init-databases-tables.sh
    healthcheck:
      << : *healthcheck
      test: pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-Vulnogramm}

  web:
    build: ./Exsample/Vulnogramm/.
    restart: always
    volumes:
      - .:/code
    expose:
      - 80
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./Vulnogramm_front/vulnogramm/.
    volumes:
      - .:/frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    restart: always
    depends_on:
      web:
        condition: service_started